-- Test 1: Generated Test
-- Source Query
SELECT TXN_SRC_KEY FROM CCAL_REPL_OWNER.STCCCALQ_GG

-- Target Query
SELECT TXN_SRC_KEY FROM CCAL_OWNER.CCAL_TXN_SRC_STG_TBL


-- Test 2: Generated Test
-- Source Query
SELECT TXN_SRC_KEY FROM CCAL_OWNER.CCAL_SRC_STG_TBL

-- Target Query
SELECT TXN_SRC_KEY FROM CCAL_OWNER.CCAL_TXN_SRC_STG_TBL


-- Test 3: Generated Test
-- Source Query
SELECT DISTINCT RULE_CODE AS TRANS_TP_CODE FROM CIRD_OWNER.RULE

-- Target Query
SELECT DISTINCT TXN_TP_CODE AS TRANS_TP_CODE FROM CCAL_OWNER.CCAL_TXN_SRC_STG_TBL


-- Test 4: Generated Test
-- Source Query
SELECT COUNT(*) AS NOT_NULL_COUNT FROM CCAL_REPL_OWNER.STCCCALQ_GG WHERE TXN_SRC_KEY IS NOT NULL

-- Target Query
SELECT COUNT(*) AS TOTAL_COUNT FROM CCAL_REPL_OWNER.STCCCALQ_GG


-- Test 5: Generated Test
-- Source Query
SELECT COUNT(*) AS NOT_NULL_COUNT FROM CCAL_OWNER.CCAL_SRC_STG_TBL WHERE TXN_SRC_KEY IS NOT NULL

-- Target Query
SELECT COUNT(*) AS TOTAL_COUNT FROM CCAL_OWNER.CCAL_SRC_STG_TBL


-- Test 6: Generated Test
-- Source Query
SELECT COUNT(*) AS NOT_NULL_COUNT FROM CIRD_OWNER.RULE WHERE RULE_CODE IS NOT NULL

-- Target Query
SELECT COUNT(*) AS TOTAL_COUNT FROM CIRD_OWNER.RULE


-- Test 7: Generated Test
-- Source Query
SELECT COUNT(*) AS row_count FROM CCAL_REPL_OWNER.STCCCALQ_GG GG JOIN CCAL_OWNER.CCAL_SRC_STG_TBL SRC ON GG.TXN_SRC_KEY = SRC.TXN_SRC_KEY JOIN CIRD_OWNER.RULE R ON R.RULE_CODE = SRC.TRANS_TP_CODE

-- Target Query
SELECT COUNT(*) AS row_count FROM CCAL_OWNER.CCAL_TXN_SRC_STG_TBL

