-- AVY_FACT_SIDE E2E INSERT (Phase 4 clean approach)
-- Generated: DRD-column-list + TXN source data via control table service
-- Datasource: LH (id=3) > IKOROSTELEV.AVY_FACT_SIDE
-- Result: 5 rows loaded, R4 PASS

INSERT INTO IKOROSTELEV.AVY_FACT_SIDE (
    EXG_DIM_ID,
    AR_DIM_ID,
    OFST_AR_DIM_ID,
    ACG_TP_DIM_ID,
    CASH_POS_TP_DIM_ID,
    SBC_CCY_DIM_ID,
    SEC_PD_DIM_ID,
    CASH_PD_DIM_ID,
    LGCY_CNCL_CMPLN_RSN_DIM_ID,
    LGCY_CNCL_CMPLN_SRC_DIM_ID,
    LGCY_MKT_TP_DIM_ID,
    LGCY_TRD_CPCTY_TP_DIM_ID,
    SRC_PCS_TP_DIM_ID,
    SRC_ENTR_CNL_TP_DIM_ID,
    TRD_SLCT_TP_DIM_ID,
    TXN_SRC_STM_DIM_ID,
    REL_TXN_SRC_STM_DIM_ID,
    BKR_AR_DIM_ID,
    TD_DIM_ID,
    TD,
    SD_DIM_ID,
    TXN_ID,
    CRT_DTM,
    CRT_USR_NM,
    ACTV_F,
    LAST_UDT_USR_NM,
    LAST_UDT_DTM
)
SELECT
    -1 AS EXG_DIM_ID,
    NVL(TXN.AR_ID, -1) AS AR_DIM_ID,
    -1 AS OFST_AR_DIM_ID,
    -1 AS ACG_TP_DIM_ID,
    -1 AS CASH_POS_TP_DIM_ID,
    -1 AS SBC_CCY_DIM_ID,
    -1 AS SEC_PD_DIM_ID,
    -1 AS CASH_PD_DIM_ID,
    NVL(TXN.LGCY_CNCL_CMPLN_RSN_TP_ID, -1) AS LGCY_CNCL_CMPLN_RSN_DIM_ID,
    NVL(TXN.LGCY_CNCL_CMPLN_SRC_TP_ID, -1) AS LGCY_CNCL_CMPLN_SRC_DIM_ID,
    NVL(TXN.LGCY_MKT_TP_ID, -1) AS LGCY_MKT_TP_DIM_ID,
    NVL(TXN.LGCY_TRD_CPCTY_TP_ID, -1) AS LGCY_TRD_CPCTY_TP_DIM_ID,
    NVL(TXN.SRC_PCS_TP_ID, -1) AS SRC_PCS_TP_DIM_ID,
    -1 AS SRC_ENTR_CNL_TP_DIM_ID,
    -1 AS TRD_SLCT_TP_DIM_ID,
    -1 AS TXN_SRC_STM_DIM_ID,
    -1 AS REL_TXN_SRC_STM_DIM_ID,
    NVL(TXN.AR_ID, -1) AS BKR_AR_DIM_ID,
    -1 AS TD_DIM_ID,
    NVL(TXN.TD, SYSDATE) AS TD,
    -1 AS SD_DIM_ID,
    TXN.TXN_ID AS TXN_ID,
    NVL(TXN.CRT_DTM, SYSDATE) AS CRT_DTM,
    NVL(TXN.CRT_USR_NM, 'SYSTEM') AS CRT_USR_NM,
    NVL(TXN.ACTV_F, 'Y') AS ACTV_F,
    NVL(TXN.LAST_UDT_USR_NM, 'SYSTEM') AS LAST_UDT_USR_NM,
    NVL(TXN.LAST_UDT_DTM, SYSDATE) AS LAST_UDT_DTM
FROM CCAL_REPL_OWNER.TXN TXN
WHERE TXN.ACTV_F = 'Y'
AND ROWNUM <= 5