
	merge  into	TAXLOT_OWNER.OPN_TAX_LOTS_NON_BKR_FACT T 
	using	     
	( 
		select SRC_STM_CD,
	AR_ID,
	CIRD_PD_ID,
	CCAL_PD_ID,
	ACG_TP_CD,
	TAX_LOT_EXT_REFR_KEY_PRIM,
	TAX_LOT_EXT_REFR_KEY_SCDY,
	TAX_LOT_EXT_REFR_KEY_TRTY,
	TAX_LOT_EXT_REFR_KEY_QTRNY,
	END_DT,
	EFF_DT,
	ACG_TP_NM,
	ACQ_DT,
	ADJ_COST,
	CCY_CD,
	CTF_NUM,
	CTF_NUM_PFX,
	COST_BSS_LEGS_CVR_CD,
	DISALWD_WASH_SALE_AMT,
	EXG_RATE,
	FAIR_MKT_VAL_OF_GIFT_OR_INHTN,
	GIFT_DT,
	POS_INCPTN_DT,
	LONG_SHRT_POS_CD,
	LOSS_NOT_ALWD_F,
	LIFE_TO_DTD_MKT_DCN,
	MISS_COST_BSS_F,
	ADJ_COST_NOT_ACRT_F,
	OPN_PRC_FCTR,
	OPN_TXN_EV_TP,
	COST_AMT,
	ORIG_EV_TP,
	ORIG_PRC,
	ORIG_PROCD,
	ORIG_TXN_TP_CD,
	PREM_AMT,
	QTY,
	SRC_RCRD_TP_CD,
	RVST_LOT_F,
	SD,
	TRD_NUM,
	TXN_INTT_DT,
	TXN_TP_CD,
	UC,
	SBC_UC,
	WASH_SALE_F,
	ZERO_COST_BSS_F,
	WASH_SALE_TP,
	SBC_DISALWD_WASH_SALE_AMT,
	SBC_ADJ_COST,
	SBC_FAIR_MKT_VAL,
	SBC_OPN_PRC_FCTR,
	SBC_COST_AMT,
	SBC_ORIG_PRC,
	SBC_ORIG_PROCD,
	SRC_STM_ID,
	SRC_STM_NM,
	ACG_TP_ID,
	TAX_LOT_TP,
	COST_BSS_LEGS_CVR_F,
	MISS_IVS_COST_F,
	SESN_NUM,
	CRT_DTM,
	CRT_USR_NM,
	LAST_UDT_DTM,
	LAST_UDT_USR_NM, 	IND_UPDATE from 
			(         
				select 	 	 	SRC_STM_DIM.SRC_STM_CD SRC_STM_CD,
	OPN_TAX_LOTS_NONBKR_TGT.AR_ID AR_ID,
	CCAL_CIRD_PD_MAP_1.CIRD_PD_ID CIRD_PD_ID,
	OPN_TAX_LOTS_NONBKR_TGT.CCAL_PD_ID CCAL_PD_ID,
	OPN_TAX_LOTS_NONBKR_TGT.AC_TP_CODE ACG_TP_CD,
	OPN_TAX_LOTS_NONBKR_TGT.TAX_LOT_EXT_REFR_KEY_PRIM TAX_LOT_EXT_REFR_KEY_PRIM,
	OPN_TAX_LOTS_NONBKR_TGT.TAX_LOT_EXT_REFR_KEY_SCDY TAX_LOT_EXT_REFR_KEY_SCDY,
	OPN_TAX_LOTS_NONBKR_TGT.TAX_LOT_EXT_REFR_KEY_TRTY TAX_LOT_EXT_REFR_KEY_TRTY,
	OPN_TAX_LOTS_NONBKR_TGT.TAX_LOT_EXT_REFR_KEY_QTRNY TAX_LOT_EXT_REFR_KEY_QTRNY,
	OPN_TAX_LOTS_NONBKR_TGT.EFF_TO_DT END_DT,
	OPN_TAX_LOTS_NONBKR_TGT.EFF_FM_DT EFF_DT,
	ACG_TP_DIM.ACG_TP_NM ACG_TP_NM,
	OPN_TAX_LOTS_NONBKR_TGT.ACQ_DT ACQ_DT,
	case when  (OPN_TAX_LOTS_NONBKR_TGT.STM_BASE_ISO_CCY_CODE='USD' or 
(OPN_TAX_LOTS_NONBKR_TGT.SBC_EXG_RATE  is NULL OR OPN_TAX_LOTS_NONBKR_TGT.SBC_EXG_RATE = 0)) 
THEN OPN_TAX_LOTS_NONBKR_TGT.SBC_ASOF_ADJ_COST_AMT
ELSE 
    OPN_TAX_LOTS_NONBKR_TGT.SBC_ASOF_ADJ_COST_AMT * OPN_TAX_LOTS_NONBKR_TGT.SBC_EXG_RATE 
END ADJ_COST,
	OPN_TAX_LOTS_NONBKR_TGT.STM_BASE_ISO_CCY_CODE CCY_CD,
	OPN_TAX_LOTS_NONBKR_TGT.TAX_LOT_CTF_NUM CTF_NUM,
	OPN_TAX_LOTS_NONBKR_TGT.TAX_LOT_CTF_NUM_PFX CTF_NUM_PFX,
	OPN_TAX_LOTS_NONBKR_TGT.CVRD_UNCVRD COST_BSS_LEGS_CVR_CD,
	OPN_TAX_LOTS_NONBKR_TGT.SBC_WASH_SALE_AMT DISALWD_WASH_SALE_AMT,
	OPN_TAX_LOTS_NONBKR_TGT.SBC_EXG_RATE EXG_RATE,
	case when  (OPN_TAX_LOTS_NONBKR_TGT.STM_BASE_ISO_CCY_CODE='USD' or (OPN_TAX_LOTS_NONBKR_TGT.SBC_EXG_RATE  is NULL OR OPN_TAX_LOTS_NONBKR_TGT.SBC_EXG_RATE = 0)) THEN OPN_TAX_LOTS_NONBKR_TGT.SBC_ASOF_FAIR_MKT_VAL_AMT
ELSE 
   OPN_TAX_LOTS_NONBKR_TGT.SBC_ASOF_FAIR_MKT_VAL_AMT * OPN_TAX_LOTS_NONBKR_TGT.SBC_EXG_RATE 
END FAIR_MKT_VAL_OF_GIFT_OR_INHTN,
	OPN_TAX_LOTS_NONBKR_TGT.GIFT_DT GIFT_DT,
	OPN_TAX_LOTS_NONBKR_TGT.POS_INCPTN_DT POS_INCPTN_DT,
	OPN_TAX_LOTS_NONBKR_TGT.POS_LONG_SHRT_CODE LONG_SHRT_POS_CD,
	NULL LOSS_NOT_ALWD_F,
	NULL LIFE_TO_DTD_MKT_DCN,
	CASE
WHEN (OPN_TAX_LOTS_NONBKR_TGT.MISS_COST_F= 'Y' OR OPN_TAX_LOTS_NONBKR_TGT.NULL_BSS_F = 'Y')
                          THEN 'Y'
                        ELSE 'N'
                     END MISS_COST_BSS_F,
	OPN_TAX_LOTS_NONBKR_TGT.NULL_BSS_F ADJ_COST_NOT_ACRT_F,
	case when  (OPN_TAX_LOTS_NONBKR_TGT.STM_BASE_ISO_CCY_CODE='USD' or (OPN_TAX_LOTS_NONBKR_TGT.SBC_EXG_RATE  is NULL OR OPN_TAX_LOTS_NONBKR_TGT.SBC_EXG_RATE = 0)) THEN OPN_TAX_LOTS_NONBKR_TGT.SBC_OPN_PRC_FCTR
ELSE 
    OPN_TAX_LOTS_NONBKR_TGT.SBC_OPN_PRC_FCTR * OPN_TAX_LOTS_NONBKR_TGT.SBC_EXG_RATE 
END OPN_PRC_FCTR,
	CL_VAL1.CL_VAL_NM OPN_TXN_EV_TP,
	case when  (OPN_TAX_LOTS_NONBKR_TGT.STM_BASE_ISO_CCY_CODE='USD' or (OPN_TAX_LOTS_NONBKR_TGT.SBC_EXG_RATE  is NULL OR OPN_TAX_LOTS_NONBKR_TGT.SBC_EXG_RATE = 0)) THEN OPN_TAX_LOTS_NONBKR_TGT.NML_ASOF_CRN_COST_AMT
ELSE 
    OPN_TAX_LOTS_NONBKR_TGT.NML_ASOF_CRN_COST_AMT * OPN_TAX_LOTS_NONBKR_TGT.SBC_EXG_RATE 
END COST_AMT,
	NULL ORIG_EV_TP,
	case when  (OPN_TAX_LOTS_NONBKR_TGT.STM_BASE_ISO_CCY_CODE='USD' or (OPN_TAX_LOTS_NONBKR_TGT.SBC_EXG_RATE  is NULL OR OPN_TAX_LOTS_NONBKR_TGT.SBC_EXG_RATE = 0)) THEN OPN_TAX_LOTS_NONBKR_TGT.SBC_ORIG_PRC
ELSE 
    OPN_TAX_LOTS_NONBKR_TGT.SBC_ORIG_PRC * OPN_TAX_LOTS_NONBKR_TGT.SBC_EXG_RATE 
END ORIG_PRC,
	case when  (OPN_TAX_LOTS_NONBKR_TGT.STM_BASE_ISO_CCY_CODE='USD' or (OPN_TAX_LOTS_NONBKR_TGT.SBC_EXG_RATE  is NULL OR OPN_TAX_LOTS_NONBKR_TGT.SBC_EXG_RATE = 0)) THEN 
OPN_TAX_LOTS_NONBKR_TGT.SBC_ORIG_PROCD_AMT
ELSE 
    OPN_TAX_LOTS_NONBKR_TGT.SBC_ORIG_PROCD_AMT * OPN_TAX_LOTS_NONBKR_TGT.SBC_EXG_RATE 
END ORIG_PROCD,
	NULL ORIG_TXN_TP_CD,
	null PREM_AMT,
	OPN_TAX_LOTS_NONBKR_TGT.TAX_LOT_ASOF_QTY QTY,
	CL_VAL.CL_VAL_CODE SRC_RCRD_TP_CD,
	OPN_TAX_LOTS_NONBKR_TGT.RVST_F RVST_LOT_F,
	OPN_TAX_LOTS_NONBKR_TGT.SD SD,
	OPN_TAX_LOTS_NONBKR_TGT.TRD_NUM TRD_NUM,
	OPN_TAX_LOTS_NONBKR_TGT.TXN_INIT_DT TXN_INTT_DT,
	NULL TXN_TP_CD,
	case when  (OPN_TAX_LOTS_NONBKR_TGT.STM_BASE_ISO_CCY_CODE='USD' or (OPN_TAX_LOTS_NONBKR_TGT.SBC_EXG_RATE  is NULL OR OPN_TAX_LOTS_NONBKR_TGT.SBC_EXG_RATE = 0)) THEN  
OPN_TAX_LOTS_NONBKR_TGT.SBC_OPN_PER_UC_AMT 
ELSE  
    OPN_TAX_LOTS_NONBKR_TGT.SBC_OPN_PER_UC_AMT * OPN_TAX_LOTS_NONBKR_TGT.SBC_EXG_RATE  
END UC,
	case when  (OPN_TAX_LOTS_NONBKR_TGT.STM_BASE_ISO_CCY_CODE='USD' or (OPN_TAX_LOTS_NONBKR_TGT.SBC_EXG_RATE  is NULL OR OPN_TAX_LOTS_NONBKR_TGT.SBC_EXG_RATE = 0)) THEN  
OPN_TAX_LOTS_NONBKR_TGT.SBC_OPN_PER_UC_AMT 
ELSE  
    OPN_TAX_LOTS_NONBKR_TGT.SBC_OPN_PER_UC_AMT * OPN_TAX_LOTS_NONBKR_TGT.SBC_EXG_RATE  
END SBC_UC,
	OPN_TAX_LOTS_NONBKR_TGT.WASH_SALE_F WASH_SALE_F,
	OPN_TAX_LOTS_NONBKR_TGT.ZERO_BSS_IND_F ZERO_COST_BSS_F,
	CASE   
WHEN OPN_TAX_LOTS_NONBKR_TGT.WASH_SALE_F ='Y' 
AND OPN_TAX_LOTS_NONBKR_TGT.SBC_WASH_SALE_AMT = 0    THEN 'CBW' 
WHEN OPN_TAX_LOTS_NONBKR_TGT.WASH_SALE_F ='Y' 
AND OPN_TAX_LOTS_NONBKR_TGT.SBC_WASH_SALE_AMT > 0    THEN 'BOTHW' 
WHEN OPN_TAX_LOTS_NONBKR_TGT.WASH_SALE_F <> 'Y' 
AND OPN_TAX_LOTS_NONBKR_TGT.SBC_WASH_SALE_AMT > 0    THEN 'GLW' 
else null
END WASH_SALE_TP,
	OPN_TAX_LOTS_NONBKR_TGT.SBC_WASH_SALE_AMT SBC_DISALWD_WASH_SALE_AMT,
	case when  (OPN_TAX_LOTS_NONBKR_TGT.STM_BASE_ISO_CCY_CODE='USD' or (OPN_TAX_LOTS_NONBKR_TGT.SBC_EXG_RATE  is NULL OR OPN_TAX_LOTS_NONBKR_TGT.SBC_EXG_RATE = 0)) THEN  
OPN_TAX_LOTS_NONBKR_TGT.SBC_ASOF_ADJ_COST_AMT 
ELSE  
    OPN_TAX_LOTS_NONBKR_TGT.SBC_ASOF_ADJ_COST_AMT * OPN_TAX_LOTS_NONBKR_TGT.SBC_EXG_RATE  
END SBC_ADJ_COST,
	case when  (OPN_TAX_LOTS_NONBKR_TGT.STM_BASE_ISO_CCY_CODE='USD' or (OPN_TAX_LOTS_NONBKR_TGT.SBC_EXG_RATE  is NULL OR OPN_TAX_LOTS_NONBKR_TGT.SBC_EXG_RATE = 0)) THEN  
OPN_TAX_LOTS_NONBKR_TGT.SBC_ASOF_FAIR_MKT_VAL_AMT 
ELSE  
    OPN_TAX_LOTS_NONBKR_TGT.SBC_ASOF_FAIR_MKT_VAL_AMT * OPN_TAX_LOTS_NONBKR_TGT.SBC_EXG_RATE  
END SBC_FAIR_MKT_VAL,
	case when  (OPN_TAX_LOTS_NONBKR_TGT.STM_BASE_ISO_CCY_CODE='USD' or (OPN_TAX_LOTS_NONBKR_TGT.SBC_EXG_RATE  is NULL OR OPN_TAX_LOTS_NONBKR_TGT.SBC_EXG_RATE = 0)) THEN 
OPN_TAX_LOTS_NONBKR_TGT.SBC_OPN_PRC_FCTR
ELSE 
    OPN_TAX_LOTS_NONBKR_TGT.SBC_OPN_PRC_FCTR * OPN_TAX_LOTS_NONBKR_TGT.SBC_EXG_RATE 
END SBC_OPN_PRC_FCTR,
	case when  (OPN_TAX_LOTS_NONBKR_TGT.STM_BASE_ISO_CCY_CODE='USD' or (OPN_TAX_LOTS_NONBKR_TGT.SBC_EXG_RATE  is NULL OR OPN_TAX_LOTS_NONBKR_TGT.SBC_EXG_RATE = 0)) THEN 
OPN_TAX_LOTS_NONBKR_TGT.SBC_OPN_COST_AMT
ELSE 
    OPN_TAX_LOTS_NONBKR_TGT.SBC_OPN_COST_AMT * OPN_TAX_LOTS_NONBKR_TGT.SBC_EXG_RATE 
END SBC_COST_AMT,
	case when  (OPN_TAX_LOTS_NONBKR_TGT.STM_BASE_ISO_CCY_CODE='USD' or (OPN_TAX_LOTS_NONBKR_TGT.SBC_EXG_RATE  is NULL OR OPN_TAX_LOTS_NONBKR_TGT.SBC_EXG_RATE = 0)) THEN 
OPN_TAX_LOTS_NONBKR_TGT.SBC_ORIG_PRC
ELSE 
   OPN_TAX_LOTS_NONBKR_TGT.SBC_ORIG_PRC * OPN_TAX_LOTS_NONBKR_TGT.SBC_EXG_RATE 
END SBC_ORIG_PRC,
	case when  (OPN_TAX_LOTS_NONBKR_TGT.STM_BASE_ISO_CCY_CODE='USD' or (OPN_TAX_LOTS_NONBKR_TGT.SBC_EXG_RATE  is NULL OR OPN_TAX_LOTS_NONBKR_TGT.SBC_EXG_RATE = 0)) THEN 
OPN_TAX_LOTS_NONBKR_TGT.SBC_ORIG_PROCD_AMT
ELSE 
  OPN_TAX_LOTS_NONBKR_TGT.SBC_ORIG_PROCD_AMT * OPN_TAX_LOTS_NONBKR_TGT.SBC_EXG_RATE 
END SBC_ORIG_PROCD,
	SRC_STM_DIM.SRC_STM_ID SRC_STM_ID,
	SRC_STM_DIM.SRC_STM_NM SRC_STM_NM,
	ACG_TP_DIM.ACG_TP_ID ACG_TP_ID,
	CL_VAL3.CL_VAL_NM TAX_LOT_TP,
	case when OPN_TAX_LOTS_NONBKR_TGT.CVRD_UNCVRD = 'C' then 'Y'
else 'N'
end COST_BSS_LEGS_CVR_F,
	CASE
                          WHEN (OPN_TAX_LOTS_NONBKR_TGT.RVST_F<>'Y' AND (OPN_TAX_LOTS_NONBKR_TGT.MISS_COST_F = 'Y' OR OPN_TAX_LOTS_NONBKR_TGT.NULL_BSS_F = 'Y'))
                            THEN 'Y'
                            ELSE 'N'
                    END MISS_IVS_COST_F,
	#GLOBAL.GV_ODI_SESS_NO SESN_NUM,
	sysdate CRT_DTM,
	OPN_TAX_LOTS_NONBKR_TGT.CRT_USR_NM CRT_USR_NM,
	sysdate LAST_UDT_DTM,
	OPN_TAX_LOTS_NONBKR_TGT.LAST_UDT_USR_NM LAST_UDT_USR_NM, 
				 	'I' IND_UPDATE  
				from	((((((TAXLOT_STG_OWNER.OPN_TAX_LOTS_NONBKR_TGT OPN_TAX_LOTS_NONBKR_TGT  LEFT OUTER JOIN  COMMON_OWNER.SRC_STM_DIM SRC_STM_DIM  
    ON  OPN_TAX_LOTS_NONBKR_TGT.SRC_STM_ID=SRC_STM_DIM.SRC_STM_ID
     )  LEFT OUTER JOIN  (
SELECT 
  CCAL_CIRD_PD_MAP.CCAL_PD_ID AS CCAL_PD_ID ,
  CCAL_CIRD_PD_MAP.CIRD_PD_ID AS CIRD_PD_ID ,
  CCAL_CIRD_PD_MAP.ACTV_F AS ACTV_F   
FROM 
  CCAL_REPL_OWNER.CCAL_CIRD_PD_MAP CCAL_CIRD_PD_MAP  
WHERE
  (CCAL_CIRD_PD_MAP.ACTV_F='Y'
) 
  ) CCAL_CIRD_PD_MAP_1  
    ON  CCAL_CIRD_PD_MAP_1.CCAL_PD_ID= OPN_TAX_LOTS_NONBKR_TGT.CCAL_PD_ID
     )  LEFT OUTER JOIN  COMMON_OWNER.ACG_TP_DIM ACG_TP_DIM  
    ON  ACG_TP_DIM.ACG_TP_CD =OPN_TAX_LOTS_NONBKR_TGT.AC_TP_CODE
     )  LEFT OUTER JOIN  CCAL_REPL_OWNER.CL_VAL CL_VAL1  
    ON  CL_VAL1.CL_VAL_ID= OPN_TAX_LOTS_NONBKR_TGT.TAX_LOT_TXN_EV_TP_ID 
and CL_VAL1.CL_SCM_ID=86
     )  LEFT OUTER JOIN  CCAL_REPL_OWNER.CL_VAL CL_VAL2  
    ON  CL_VAL2.CL_VAL_ID= OPN_TAX_LOTS_NONBKR_TGT.ORIG_TAX_LOT_TXN_TP_ID
     )  LEFT OUTER JOIN  CCAL_REPL_OWNER.CL_VAL CL_VAL3  
    ON  CL_VAL3.CL_VAL_ID= OPN_TAX_LOTS_NONBKR_TGT.TAX_LOT_TXN_TP_ID
and CL_VAL3.CL_SCM_ID=84
     )  LEFT OUTER JOIN  CCAL_REPL_OWNER.CL_VAL CL_VAL  
    ON  CL_VAL.CL_VAL_ID= OPN_TAX_LOTS_NONBKR_TGT.SRC_RCRD_TP_ID
      where	(1=1)       
			) X     
	)  S on	
	( 		T.AR_ID=S.AR_ID
	and		T.CCAL_PD_ID=S.CCAL_PD_ID
	and		T.TAX_LOT_EXT_REFR_KEY_PRIM=S.TAX_LOT_EXT_REFR_KEY_PRIM
	and		T.TXN_INTT_DT=S.TXN_INTT_DT 	) 
	when matched then 
	update set 	T.SRC_STM_CD	= S.SRC_STM_CD,
	T.CIRD_PD_ID	= S.CIRD_PD_ID,
	T.ACG_TP_CD	= S.ACG_TP_CD,
	T.TAX_LOT_EXT_REFR_KEY_SCDY	= S.TAX_LOT_EXT_REFR_KEY_SCDY,
	T.TAX_LOT_EXT_REFR_KEY_TRTY	= S.TAX_LOT_EXT_REFR_KEY_TRTY,
	T.TAX_LOT_EXT_REFR_KEY_QTRNY	= S.TAX_LOT_EXT_REFR_KEY_QTRNY,
	T.END_DT	= S.END_DT,
	T.EFF_DT	= S.EFF_DT,
	T.ACG_TP_NM	= S.ACG_TP_NM,
	T.ACQ_DT	= S.ACQ_DT,
	T.ADJ_COST	= S.ADJ_COST,
	T.CCY_CD	= S.CCY_CD,
	T.CTF_NUM	= S.CTF_NUM,
	T.CTF_NUM_PFX	= S.CTF_NUM_PFX,
	T.COST_BSS_LEGS_CVR_CD	= S.COST_BSS_LEGS_CVR_CD,
	T.DISALWD_WASH_SALE_AMT	= S.DISALWD_WASH_SALE_AMT,
	T.EXG_RATE	= S.EXG_RATE,
	T.FAIR_MKT_VAL_OF_GIFT_OR_INHTN	= S.FAIR_MKT_VAL_OF_GIFT_OR_INHTN,
	T.GIFT_DT	= S.GIFT_DT,
	T.POS_INCPTN_DT	= S.POS_INCPTN_DT,
	T.LONG_SHRT_POS_CD	= S.LONG_SHRT_POS_CD,
	T.LOSS_NOT_ALWD_F	= S.LOSS_NOT_ALWD_F,
	T.LIFE_TO_DTD_MKT_DCN	= S.LIFE_TO_DTD_MKT_DCN,
	T.MISS_COST_BSS_F	= S.MISS_COST_BSS_F,
	T.ADJ_COST_NOT_ACRT_F	= S.ADJ_COST_NOT_ACRT_F,
	T.OPN_PRC_FCTR	= S.OPN_PRC_FCTR,
	T.OPN_TXN_EV_TP	= S.OPN_TXN_EV_TP,
	T.COST_AMT	= S.COST_AMT,
	T.ORIG_EV_TP	= S.ORIG_EV_TP,
	T.ORIG_PRC	= S.ORIG_PRC,
	T.ORIG_PROCD	= S.ORIG_PROCD,
	T.ORIG_TXN_TP_CD	= S.ORIG_TXN_TP_CD,
	T.PREM_AMT	= S.PREM_AMT,
	T.QTY	= S.QTY,
	T.SRC_RCRD_TP_CD	= S.SRC_RCRD_TP_CD,
	T.RVST_LOT_F	= S.RVST_LOT_F,
	T.SD	= S.SD,
	T.TRD_NUM	= S.TRD_NUM,
	T.TXN_TP_CD	= S.TXN_TP_CD,
	T.UC	= S.UC,
	T.SBC_UC	= S.SBC_UC,
	T.WASH_SALE_F	= S.WASH_SALE_F,
	T.ZERO_COST_BSS_F	= S.ZERO_COST_BSS_F,
	T.WASH_SALE_TP	= S.WASH_SALE_TP,
	T.SBC_DISALWD_WASH_SALE_AMT	= S.SBC_DISALWD_WASH_SALE_AMT,
	T.SBC_ADJ_COST	= S.SBC_ADJ_COST,
	T.SBC_FAIR_MKT_VAL	= S.SBC_FAIR_MKT_VAL,
	T.SBC_OPN_PRC_FCTR	= S.SBC_OPN_PRC_FCTR,
	T.SBC_COST_AMT	= S.SBC_COST_AMT,
	T.SBC_ORIG_PRC	= S.SBC_ORIG_PRC,
	T.SBC_ORIG_PROCD	= S.SBC_ORIG_PROCD,
	T.SRC_STM_ID	= S.SRC_STM_ID,
	T.SRC_STM_NM	= S.SRC_STM_NM,
	T.ACG_TP_ID	= S.ACG_TP_ID,
	T.TAX_LOT_TP	= S.TAX_LOT_TP,
	T.COST_BSS_LEGS_CVR_F	= S.COST_BSS_LEGS_CVR_F,
	T.MISS_IVS_COST_F	= S.MISS_IVS_COST_F,
	T.SESN_NUM	= S.SESN_NUM,
	T.CRT_DTM	= S.CRT_DTM,
	T.CRT_USR_NM	= S.CRT_USR_NM,
	T.LAST_UDT_DTM	= S.LAST_UDT_DTM,
	T.LAST_UDT_USR_NM	= S.LAST_UDT_USR_NM 	
		when not matched then 
	insert 	
	( 	
		T.SRC_STM_CD,
	T.AR_ID,
	T.CIRD_PD_ID,
	T.CCAL_PD_ID,
	T.ACG_TP_CD,
	T.TAX_LOT_EXT_REFR_KEY_PRIM,
	T.TAX_LOT_EXT_REFR_KEY_SCDY,
	T.TAX_LOT_EXT_REFR_KEY_TRTY,
	T.TAX_LOT_EXT_REFR_KEY_QTRNY,
	T.END_DT,
	T.EFF_DT,
	T.ACG_TP_NM,
	T.ACQ_DT,
	T.ADJ_COST,
	T.CCY_CD,
	T.CTF_NUM,
	T.CTF_NUM_PFX,
	T.COST_BSS_LEGS_CVR_CD,
	T.DISALWD_WASH_SALE_AMT,
	T.EXG_RATE,
	T.FAIR_MKT_VAL_OF_GIFT_OR_INHTN,
	T.GIFT_DT,
	T.POS_INCPTN_DT,
	T.LONG_SHRT_POS_CD,
	T.LOSS_NOT_ALWD_F,
	T.LIFE_TO_DTD_MKT_DCN,
	T.MISS_COST_BSS_F,
	T.ADJ_COST_NOT_ACRT_F,
	T.OPN_PRC_FCTR,
	T.OPN_TXN_EV_TP,
	T.COST_AMT,
	T.ORIG_EV_TP,
	T.ORIG_PRC,
	T.ORIG_PROCD,
	T.ORIG_TXN_TP_CD,
	T.PREM_AMT,
	T.QTY,
	T.SRC_RCRD_TP_CD,
	T.RVST_LOT_F,
	T.SD,
	T.TRD_NUM,
	T.TXN_INTT_DT,
	T.TXN_TP_CD,
	T.UC,
	T.SBC_UC,
	T.WASH_SALE_F,
	T.ZERO_COST_BSS_F,
	T.WASH_SALE_TP,
	T.SBC_DISALWD_WASH_SALE_AMT,
	T.SBC_ADJ_COST,
	T.SBC_FAIR_MKT_VAL,
	T.SBC_OPN_PRC_FCTR,
	T.SBC_COST_AMT,
	T.SBC_ORIG_PRC,
	T.SBC_ORIG_PROCD,
	T.SRC_STM_ID,
	T.SRC_STM_NM,
	T.ACG_TP_ID,
	T.TAX_LOT_TP,
	T.COST_BSS_LEGS_CVR_F,
	T.MISS_IVS_COST_F,
	T.SESN_NUM,
	T.CRT_DTM,
	T.CRT_USR_NM,
	T.LAST_UDT_DTM,
	T.LAST_UDT_USR_NM 	
        ) 
		values 	
		( 	
			S.SRC_STM_CD,
	S.AR_ID,
	S.CIRD_PD_ID,
	S.CCAL_PD_ID,
	S.ACG_TP_CD,
	S.TAX_LOT_EXT_REFR_KEY_PRIM,
	S.TAX_LOT_EXT_REFR_KEY_SCDY,
	S.TAX_LOT_EXT_REFR_KEY_TRTY,
	S.TAX_LOT_EXT_REFR_KEY_QTRNY,
	S.END_DT,
	S.EFF_DT,
	S.ACG_TP_NM,
	S.ACQ_DT,
	S.ADJ_COST,
	S.CCY_CD,
	S.CTF_NUM,
	S.CTF_NUM_PFX,
	S.COST_BSS_LEGS_CVR_CD,
	S.DISALWD_WASH_SALE_AMT,
	S.EXG_RATE,
	S.FAIR_MKT_VAL_OF_GIFT_OR_INHTN,
	S.GIFT_DT,
	S.POS_INCPTN_DT,
	S.LONG_SHRT_POS_CD,
	S.LOSS_NOT_ALWD_F,
	S.LIFE_TO_DTD_MKT_DCN,
	S.MISS_COST_BSS_F,
	S.ADJ_COST_NOT_ACRT_F,
	S.OPN_PRC_FCTR,
	S.OPN_TXN_EV_TP,
	S.COST_AMT,
	S.ORIG_EV_TP,
	S.ORIG_PRC,
	S.ORIG_PROCD,
	S.ORIG_TXN_TP_CD,
	S.PREM_AMT,
	S.QTY,
	S.SRC_RCRD_TP_CD,
	S.RVST_LOT_F,
	S.SD,
	S.TRD_NUM,
	S.TXN_INTT_DT,
	S.TXN_TP_CD,
	S.UC,
	S.SBC_UC,
	S.WASH_SALE_F,
	S.ZERO_COST_BSS_F,
	S.WASH_SALE_TP,
	S.SBC_DISALWD_WASH_SALE_AMT,
	S.SBC_ADJ_COST,
	S.SBC_FAIR_MKT_VAL,
	S.SBC_OPN_PRC_FCTR,
	S.SBC_COST_AMT,
	S.SBC_ORIG_PRC,
	S.SBC_ORIG_PROCD,
	S.SRC_STM_ID,
	S.SRC_STM_NM,
	S.ACG_TP_ID,
	S.TAX_LOT_TP,
	S.COST_BSS_LEGS_CVR_F,
	S.MISS_IVS_COST_F,
	S.SESN_NUM,
	S.CRT_DTM,
	S.CRT_USR_NM,
	S.LAST_UDT_DTM,
	S.LAST_UDT_USR_NM 	
		) 
  