-- Test 1: Generated Test
-- Source Query
SELECT DISTINCT TXN_SRC_KEY FROM CCAL_REPL_OWNER.STCCCALQ_GG

-- Target Query
SELECT DISTINCT TXN_SRC_KEY FROM CCAL_OWNER.CCAL_SRC_STG_TBL


-- Test 2: Generated Test
-- Source Query
SELECT DISTINCT TRANS_TP_CODE FROM CCAL_OWNER.CCAL_SRC_STG_TBL

-- Target Query
SELECT DISTINCT RULE_CODE FROM CIRD_OWNER.RULE


-- Test 3: Generated Test
-- Source Query
SELECT COUNT(*) AS NOT_NULL_COUNT FROM CCAL_REPL_OWNER.STCCCALQ_GG WHERE TXN_SRC_KEY IS NOT NULL

-- Target Query
SELECT COUNT(*) AS TOTAL_COUNT FROM CCAL_REPL_OWNER.STCCCALQ_GG


-- Test 4: Generated Test
-- Source Query
SELECT COUNT(*) AS NOT_NULL_COUNT FROM CCAL_OWNER.CCAL_SRC_STG_TBL WHERE TXN_SRC_KEY IS NOT NULL

-- Target Query
SELECT COUNT(*) AS TOTAL_COUNT FROM CCAL_OWNER.CCAL_SRC_STG_TBL


-- Test 5: Generated Test
-- Source Query
SELECT COUNT(*) AS NOT_NULL_COUNT FROM CCAL_OWNER.CCAL_SRC_STG_TBL WHERE TRANS_TP_CODE IS NOT NULL

-- Target Query
SELECT COUNT(*) AS TOTAL_COUNT FROM CCAL_OWNER.CCAL_SRC_STG_TBL


-- Test 6: Generated Test
-- Source Query
SELECT COUNT(*) AS NOT_NULL_COUNT FROM CIRD_OWNER.RULE WHERE RULE_CODE IS NOT NULL

-- Target Query
SELECT COUNT(*) AS TOTAL_COUNT FROM CIRD_OWNER.RULE


-- Test 7: Generated Test
-- Source Query
SELECT COUNT(*) AS row_count FROM CCAL_REPL_OWNER.STCCCALQ_GG WHERE TXN_SRC_KEY IS NOT NULL

-- Target Query
SELECT COUNT(*) AS row_count FROM CCAL_OWNER.CCAL_SRC_STG_TBL WHERE TXN_SRC_KEY IS NOT NULL


-- Test 8: Generated Test
-- Source Query
SELECT COUNT(*) AS row_count FROM CCAL_OWNER.CCAL_SRC_STG_TBL WHERE TRANS_TP_CODE IS NOT NULL

-- Target Query
SELECT COUNT(*) AS row_count FROM CIRD_OWNER.RULE WHERE RULE_CODE IS NOT NULL


-- Test 9: Generated Test
-- Source Query
SELECT COUNT(*) AS duplicate_count FROM CCAL_REPL_OWNER.STCCCALQ_GG GROUP BY TXN_SRC_KEY HAVING COUNT(*) > 1

-- Target Query
SELECT 0 AS expected_duplicate_count FROM DUAL


-- Test 10: Generated Test
-- Source Query
SELECT COUNT(*) AS duplicate_count FROM CCAL_OWNER.CCAL_SRC_STG_TBL GROUP BY TRANS_TP_CODE HAVING COUNT(*) > 1

-- Target Query
SELECT 0 AS duplicate_count FROM DUAL

