-- Test 1: Generated Test
-- Source Query
SELECT APA_ID, APA_TP_ID FROM CCAL_OWNER.CCAL_APA_SRC_STG_TBL

-- Target Query
SELECT APA_ID, APA_TP_ID FROM CCAL_OWNER.CCAL_TXN_AY_CL_SRC_STG_TBL


-- Test 2: Generated Test
-- Source Query
SELECT TXN_ID, APA_ID FROM CCAL_OWNER.CCAL_FIP_SRC_STG_TBL

-- Target Query
SELECT TXN_ID, APA_ID FROM CCAL_OWNER.CCAL_TXN_AY_CL_SRC_STG_TBL


-- Test 3: Generated Test
-- Source Query
SELECT TXN_ID FROM CCAL_OWNER.CCAL_SRC_STG_TBL

-- Target Query
SELECT TXN_ID FROM CCAL_OWNER.CCAL_TXN_AY_CL_SRC_STG_TBL


-- Test 4: Generated Test
-- Source Query
SELECT TXN_ID FROM CCAL_OWNER.CCAL_TXN_SRC_STG_TBL

-- Target Query
SELECT TXN_ID FROM CCAL_OWNER.CCAL_TXN_AY_CL_SRC_STG_TBL

