-- Test 1: Generated Test
-- Source Query
SELECT COUNT(*) AS record_count FROM CCAL_OWNER.CCAL_APA_SRC_STG_TBL src JOIN CCAL_OWNER.CCAL_FIP_SRC_STG_TBL tgt ON src.APA_ID = tgt.APA_ID

-- Target Query
SELECT COUNT(*) AS record_count FROM CCAL_OWNER.CCAL_SRC_STG_TBL src JOIN CCAL_OWNER.CCAL_TXN_SRC_STG_TBL tgt ON src.TXN_ID = tgt.TXN_ID


-- Test 2: Generated Test
-- Source Query
SELECT COUNT(*) AS source_count FROM CCAL_OWNER.CCAL_APA_SRC_STG_TBL a JOIN CCAL_OWNER.CCAL_FIP_SRC_STG_TBL b ON a.APA_ID = b.APA_ID

-- Target Query
SELECT COUNT(*) AS target_count FROM CCAL_OWNER.CCAL_SRC_STG_TBL c JOIN CCAL_OWNER.CCAL_TXN_SRC_STG_TBL d ON c.TXN_ID = d.TXN_ID


-- Test 3: Generated Test
-- Source Query
SELECT COUNT(*) AS source_count FROM CCAL_OWNER.CCAL_APA_SRC_STG_TBL src JOIN CCAL_OWNER.CCAL_FIP_SRC_STG_TBL tgt ON src.APA_ID = tgt.APA_ID

-- Target Query
SELECT COUNT(*) AS target_count FROM CCAL_OWNER.CCAL_APA_SRC_STG_TBL src JOIN CCAL_OWNER.CCAL_FIP_SRC_STG_TBL tgt ON src.APA_ID = tgt.APA_ID


-- Test 4: Generated Test
-- Source Query
SELECT COUNT(*) AS source_count FROM CCAL_OWNER.CCAL_APA_SRC_STG_TBL src JOIN CCAL_OWNER.CCAL_FIP_SRC_STG_TBL tgt ON src.APA_ID = tgt.APA_ID

-- Target Query
SELECT COUNT(*) AS target_count FROM CCAL_OWNER.CCAL_APA_SRC_STG_TBL src JOIN CCAL_OWNER.CCAL_FIP_SRC_STG_TBL tgt ON src.APA_ID = tgt.APA_ID


-- Test 5: Generated Test
-- Source Query
SELECT COUNT(*) AS source_count FROM CCAL_OWNER.CCAL_APA_SRC_STG_TBL src JOIN CCAL_OWNER.CCAL_FIP_SRC_STG_TBL tgt ON src.APA_ID = tgt.APA_ID

-- Target Query
SELECT COUNT(*) AS target_count FROM CCAL_OWNER.CCAL_APA_SRC_STG_TBL src JOIN CCAL_OWNER.CCAL_FIP_SRC_STG_TBL tgt ON src.APA_ID = tgt.APA_ID


-- Test 6: Generated Test
-- Source Query
SELECT COUNT(*) AS source_count FROM CCAL_OWNER.CCAL_APA_SRC_STG_TBL src JOIN CCAL_OWNER.CCAL_FIP_SRC_STG_TBL tgt ON src.APA_ID = tgt.APA_ID

-- Target Query
SELECT COUNT(*) AS target_count FROM CCAL_OWNER.CCAL_SRC_STG_TBL src JOIN CCAL_OWNER.CCAL_TXN_SRC_STG_TBL tgt ON src.TXN_ID = tgt.TXN_ID


-- Test 7: Generated Test
-- Source Query
SELECT COUNT(*) AS source_count FROM CCAL_OWNER.CCAL_APA_SRC_STG_TBL a JOIN CCAL_OWNER.CCAL_FIP_SRC_STG_TBL b ON a.APA_ID = b.APA_ID

-- Target Query
SELECT COUNT(*) AS target_count FROM CCAL_OWNER.CCAL_SRC_STG_TBL c JOIN CCAL_OWNER.CCAL_TXN_SRC_STG_TBL d ON c.TXN_ID = d.TXN_ID


-- Test 8: Generated Test
-- Source Query
SELECT COUNT(*) AS record_count FROM CCAL_OWNER.CCAL_APA_SRC_STG_TBL src JOIN CCAL_OWNER.CCAL_FIP_SRC_STG_TBL tgt ON src.APA_ID = tgt.APA_ID

-- Target Query
SELECT COUNT(*) AS record_count FROM CCAL_OWNER.CCAL_SRC_STG_TBL src JOIN CCAL_OWNER.CCAL_TXN_SRC_STG_TBL tgt ON src.TXN_ID = tgt.TXN_ID


-- Test 9: Generated Test
-- Source Query
SELECT COUNT(*) AS source_count FROM CCAL_OWNER.CCAL_APA_SRC_STG_TBL a JOIN CCAL_OWNER.CCAL_FIP_SRC_STG_TBL f ON a.APA_ID = f.APA_ID

-- Target Query
SELECT COUNT(*) AS target_count FROM CCAL_OWNER.CCAL_APA_SRC_STG_TBL a JOIN CCAL_OWNER.CCAL_FIP_SRC_STG_TBL f ON a.APA_ID = f.APA_ID


-- Test 10: Generated Test
-- Source Query
SELECT COUNT(*) AS record_count FROM CCAL_OWNER.CCAL_APA_SRC_STG_TBL src JOIN CCAL_OWNER.CCAL_FIP_SRC_STG_TBL tgt ON src.APA_ID = tgt.APA_ID

-- Target Query
SELECT COUNT(*) AS record_count FROM CCAL_OWNER.CCAL_SRC_STG_TBL src JOIN CCAL_OWNER.CCAL_TXN_SRC_STG_TBL tgt ON src.TXN_ID = tgt.TXN_ID

