import requests
BASE='http://localhost:8550'

def q(sql):
    r=requests.post(f"{BASE}/api/datasources/2/query",json={"sql":sql,"limit":200},timeout=120)
    if r.status_code!=200:
        return None, f"HTTP {r.status_code}: {r.text[:200]}"
    data=r.json()
    if isinstance(data,dict) and data.get('detail'):
        return None, str(data['detail'])
    rows=data.get('rows',[])
    return rows, None

tests=[
("Base joined row count", "SELECT COUNT(*) CNT FROM CCAL_OWNER.TXN t JOIN CDS_STG_OWNER.STCCCALQ_GG_VW s ON s.TXN_SRC_KEY=t.TXN_SRC_KEY WHERE t.TD=DATE '2026-03-30' AND t.SRC_STM_ID IN (29,30,71,72)"),
("WS_EXECUTION_SUBTYPE populated", "SELECT COUNT(*) CNT FROM CCAL_OWNER.TXN t JOIN CDS_STG_OWNER.STCCCALQ_GG_VW s ON s.TXN_SRC_KEY=t.TXN_SRC_KEY WHERE t.TD=DATE '2026-03-30' AND t.SRC_STM_ID IN (29,30,71,72) AND s.WS_EXECUTION_SUBTYPE IS NULL"),
("WS_CNX_IND populated", "SELECT COUNT(*) CNT FROM CCAL_OWNER.TXN t JOIN CDS_STG_OWNER.STCCCALQ_GG_VW s ON s.TXN_SRC_KEY=t.TXN_SRC_KEY WHERE t.TD=DATE '2026-03-30' AND t.SRC_STM_ID IN (29,30,71,72) AND s.WS_CNX_IND IS NULL"),
("EXEC_SBTP_ID mapped from WS_EXECUTION_SUBTYPE", "SELECT COUNT(*) CNT FROM CCAL_OWNER.TXN t JOIN CDS_STG_OWNER.STCCCALQ_GG_VW s ON s.TXN_SRC_KEY=t.TXN_SRC_KEY LEFT JOIN CCAL_OWNER.CL_VAL cv ON cv.CL_VAL_CODE=s.WS_EXECUTION_SUBTYPE WHERE t.TD=DATE '2026-03-30' AND t.SRC_STM_ID IN (29,30,71,72) AND s.WS_EXECUTION_SUBTYPE IS NOT NULL AND NVL(t.EXEC_SBTP_ID,-1)<>NVL(cv.CL_VAL_ID,-1)"),
("SRC_PCS_TP_ID mapped from WS_CNX_IND", "SELECT COUNT(*) CNT FROM CCAL_OWNER.TXN t JOIN CDS_STG_OWNER.STCCCALQ_GG_VW s ON s.TXN_SRC_KEY=t.TXN_SRC_KEY LEFT JOIN CCAL_OWNER.SRC_PCS_TP p ON p.SRC_PCS_TP_CODE=s.WS_CNX_IND WHERE t.TD=DATE '2026-03-30' AND t.SRC_STM_ID IN (29,30,71,72) AND s.WS_CNX_IND IS NOT NULL AND NVL(t.SRC_PCS_TP_ID,-1)<>NVL(p.SRC_PCS_TP_ID,-1)"),
("TXN_SBTP_ID mapped from WS_SUBTYPE when present", "SELECT COUNT(*) CNT FROM CCAL_OWNER.TXN t JOIN CDS_STG_OWNER.STCCCALQ_GG_VW s ON s.TXN_SRC_KEY=t.TXN_SRC_KEY LEFT JOIN CCAL_OWNER.CL_VAL cv ON cv.CL_VAL_CODE=s.WS_SUBTYPE WHERE t.TD=DATE '2026-03-30' AND t.SRC_STM_ID IN (29,30,71,72) AND s.WS_SUBTYPE IS NOT NULL AND NVL(t.TXN_SBTP_ID,-1)<>NVL(cv.CL_VAL_ID,-1)"),
("TXN_SBTP_ID null when WS_SUBTYPE null", "SELECT COUNT(*) CNT FROM CCAL_OWNER.TXN t JOIN CDS_STG_OWNER.STCCCALQ_GG_VW s ON s.TXN_SRC_KEY=t.TXN_SRC_KEY WHERE t.TD=DATE '2026-03-30' AND t.SRC_STM_ID IN (29,30,71,72) AND s.WS_SUBTYPE IS NULL AND t.TXN_SBTP_ID IS NOT NULL"),
("Rule text links to active CDSM rule when present", "SELECT COUNT(*) CNT FROM CCAL_OWNER.TXN t JOIN CDS_STG_OWNER.STCCCALQ_GG_VW s ON s.TXN_SRC_KEY=t.TXN_SRC_KEY LEFT JOIN CCAL_OWNER.CDSM_RULE_MAP m ON m.TRLR_RULE_TXT=s.WS_TRAILER_RULE_TEXT_MATCH AND m.ACTV_F='Y' WHERE t.TD=DATE '2026-03-30' AND t.SRC_STM_ID IN (29,30,71,72) AND s.WS_TRAILER_RULE_TEXT_MATCH IS NOT NULL AND m.CDSM_RULE_MAP_ID IS NULL"),
("When rule text present WS_EXECUTION_SUBTYPE equals rule EXEC_SBTP_CD", "SELECT COUNT(*) CNT FROM CCAL_OWNER.TXN t JOIN CDS_STG_OWNER.STCCCALQ_GG_VW s ON s.TXN_SRC_KEY=t.TXN_SRC_KEY JOIN CCAL_OWNER.CDSM_RULE_MAP m ON m.TRLR_RULE_TXT=s.WS_TRAILER_RULE_TEXT_MATCH AND m.ACTV_F='Y' WHERE t.TD=DATE '2026-03-30' AND t.SRC_STM_ID IN (29,30,71,72) AND m.EXEC_SBTP_CD IS NOT NULL AND NVL(s.WS_EXECUTION_SUBTYPE,'~')<>NVL(m.EXEC_SBTP_CD,'~')"),
("APA exists for each parsed TXN", "SELECT COUNT(*) CNT FROM CCAL_OWNER.TXN t JOIN CDS_STG_OWNER.STCCCALQ_GG_VW s ON s.TXN_SRC_KEY=t.TXN_SRC_KEY LEFT JOIN CCAL_OWNER.APA a ON a.EXEC_ID=t.TXN_ID WHERE t.TD=DATE '2026-03-30' AND t.SRC_STM_ID IN (29,30,71,72) AND a.APA_ID IS NULL"),
("FIP rows (if any) have valid APA for parsed TXN", "SELECT COUNT(*) CNT FROM CCAL_OWNER.FIP f LEFT JOIN CCAL_OWNER.APA a ON a.APA_ID=f.APA_ID LEFT JOIN CCAL_OWNER.TXN t ON t.TXN_ID=a.EXEC_ID WHERE t.TD=DATE '2026-03-30' AND t.SRC_STM_ID IN (29,30,71,72) AND a.APA_ID IS NULL"),
("TXN_RLTNP rows for parsed TXN have valid SRC/TRGT txn ids", "SELECT COUNT(*) CNT FROM CCAL_OWNER.TXN_RLTNP r JOIN CCAL_OWNER.TXN bt ON (bt.TXN_ID=r.SRC_TXN_ID OR bt.TXN_ID=r.TRGT_TXN_ID) LEFT JOIN CCAL_OWNER.TXN s ON s.TXN_ID=r.SRC_TXN_ID LEFT JOIN CCAL_OWNER.TXN t ON t.TXN_ID=r.TRGT_TXN_ID WHERE bt.TD=DATE '2026-03-30' AND bt.SRC_STM_ID IN (29,30,71,72) AND (s.TXN_ID IS NULL OR t.TXN_ID IS NULL)")
]
for name,sql in tests:
    rows,err=q(sql)
    if err:
        print(name,'ERR',err)
    else:
        print(name, rows[0] if rows else None)
