-- Test 1: Generated Test
-- Source Query
SELECT COUNT(*) AS source_count FROM CCAL_OWNER.CCAL_SRC_STG_TBL

-- Target Query
SELECT COUNT(*) AS target_count FROM CCAL_OWNER.TXN WHERE EXISTS (SELECT 1 FROM CCAL_OWNER.CCAL_SRC_STG_TBL WHERE CCAL_OWNER.CCAL_SRC_STG_TBL.TXN_SRC_KEY = CCAL_OWNER.TXN.TXN_SRC_KEY)


-- Test 2: Generated Test
-- Source Query
SELECT COUNT(*) AS NULL_COUNT FROM CCAL_OWNER.TXN WHERE TXN_SRC_KEY IS NULL

-- Target Query
SELECT 0 AS EXPECTED_COUNT FROM DUAL


-- Test 3: Generated Test
-- Source Query
SELECT COUNT(*) AS NULL_COUNT FROM CCAL_OWNER.TXN WHERE TXN_TP_ID IS NULL

-- Target Query
SELECT 0 AS EXPECTED_NULL_COUNT FROM DUAL


-- Test 4: Generated Test
-- Source Query
SELECT COUNT(*) AS invalid_date_count FROM CCAL_OWNER.CCAL_SRC_STG_TBL WHERE SRC_ENTR_DTM IS NULL OR SRC_ENTR_DTM NOT BETWEEN TO_DATE('1900-01-01', 'YYYY-MM-DD') AND TO_DATE('9999-12-31', 'YYYY-MM-DD')

-- Target Query
SELECT COUNT(*) AS invalid_date_count FROM CCAL_OWNER.TXN WHERE SRC_ENTR_DTM IS NULL OR SRC_ENTR_DTM NOT BETWEEN TO_DATE('1900-01-01', 'YYYY-MM-DD') AND TO_DATE('9999-12-31', 'YYYY-MM-DD')


-- Test 5: Generated Test
-- Source Query
SELECT RULE_CODE FROM CIRD_OWNER.RULE GROUP BY RULE_CODE HAVING COUNT(*) > 1

-- Target Query
SELECT COUNT(*) FROM DUAL


-- Test 6: Generated Test
-- Source Query
SELECT COUNT(*) AS invalid_date_ranges FROM CIRD_OWNER.RULE WHERE EFF_FM_DT > EFF_TO_DT

-- Target Query
SELECT 0 AS expected_invalid_date_ranges FROM DUAL


-- Test 7: Generated Test
-- Source Query
SELECT COUNT(*) AS NULL_COUNT FROM CCAL_OWNER.FIP WHERE FIP_SRC_KEY IS NULL

-- Target Query
SELECT 0 AS EXPECTED_NULL_COUNT FROM DUAL


-- Test 8: Generated Test
-- Source Query
SELECT COUNT(*) AS NEGATIVE_COUNT FROM CCAL_OWNER.FIP WHERE FIP_ORIG_AMT < 0

-- Target Query
SELECT 0 AS EXPECTED_COUNT FROM DUAL

