PROTOCOL=http
ODI_SECU_WORK_REP=ODINGEDW1224_WRKREP
JMXPORT=
JMXPROTOCOL=rmi
ODI_MASTER_TIMESTAMP=
ODI_KEYSTORE_ENCODED_PASS=
ODI_KEY_ENCODED_PASS=
ODI_TRUST_STORE_ENCODED_PASS=
ODI_CONNECTION_RETRY_COUNT=0
ODI_CONNECTION_RETRY_DELAY=7000
ProductHome=C:/Oracle/odi/v1224
DomainHome=C:/GIT_Repo/db-testing-tool/_odi_domain
ODI_EXCLUDED_CIPHERS=
